# Build an extended ETF universe for blockr.portfolio
#
# Curated from the common UCITS + US ETF landscape. Covers major asset
# classes, regions, sectors, themes, factors, and fixed income. Aims for
# what a Swiss-retail investor (via a broker like Swiss Quote) could
# realistically access.
#
# This is curated by hand — not a live scrape of Swiss Quote or justETF.
# That's a follow-up (needs platform access). TER/AUM values are
# approximated from public issuer factsheets circa 2024.
#
# Run: Rscript data-raw/build-extended-universe.R
# Output: inst/extdata/portfolio_dm.rds

library(dm)
library(quantmod)

# -- Universe definition -------------------------------------------------------

# Each row = one tradeable ticker. Yahoo ticker conventions:
#   US ETFs:     plain symbol (SPY, VTI)
#   UCITS LSE:   .L (CSPX.L, VWRA.L)
#   UCITS Xetra: .DE (SXR8.DE, VWCE.DE)
#   UCITS Swiss: .SW (CSSMI.SW)
#   UCITS AMS:   .AS (VWRL.AS)

u <- rbind(
  # --- Global broad ------------------------------------------------------
  data.frame(ticker="VT",     name="Vanguard Total World",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Total Market", sector=NA, theme=NA,
    expense_ratio=0.0007, distribution_policy="distributing",
    domicile="US", aum=45000),
  data.frame(ticker="ACWI",   name="iShares MSCI ACWI",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Total Market", sector=NA, theme=NA,
    expense_ratio=0.0032, distribution_policy="distributing",
    domicile="US", aum=22000),
  data.frame(ticker="IWDA.L", name="iShares Core MSCI World UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Developed World", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="accumulating",
    domicile="IE", aum=97000),
  data.frame(ticker="SWDA.L", name="iShares MSCI World UCITS (Acc, LSE)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Developed World", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="accumulating",
    domicile="IE", aum=97000),
  data.frame(ticker="VWCE.DE", name="Vanguard FTSE All-World UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Total Market", sector=NA, theme=NA,
    expense_ratio=0.0022, distribution_policy="accumulating",
    domicile="IE", aum=18000),
  data.frame(ticker="VWRL.L", name="Vanguard FTSE All-World UCITS (Dist)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Total Market", sector=NA, theme=NA,
    expense_ratio=0.0022, distribution_policy="distributing",
    domicile="IE", aum=7500),

  # --- US broad ----------------------------------------------------------
  data.frame(ticker="VTI",    name="Vanguard Total US Stock",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Total Market", sector=NA, theme=NA,
    expense_ratio=0.0003, distribution_policy="distributing",
    domicile="US", aum=420000),
  data.frame(ticker="IVV",    name="iShares Core S&P 500",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Large Cap", sector=NA, theme=NA,
    expense_ratio=0.0003, distribution_policy="distributing",
    domicile="US", aum=470000),
  data.frame(ticker="SPY",    name="SPDR S&P 500",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Large Cap", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=520000),
  data.frame(ticker="CSPX.L", name="iShares Core S&P 500 UCITS (Acc)",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Large Cap", sector=NA, theme=NA,
    expense_ratio=0.0007, distribution_policy="accumulating",
    domicile="IE", aum=85000),
  data.frame(ticker="VUSA.L", name="Vanguard S&P 500 UCITS (Dist)",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Large Cap", sector=NA, theme=NA,
    expense_ratio=0.0007, distribution_policy="distributing",
    domicile="IE", aum=38000),

  # --- US size/style -----------------------------------------------------
  data.frame(ticker="VUG",    name="Vanguard Growth",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Growth", sector=NA, theme=NA,
    expense_ratio=0.0004, distribution_policy="distributing",
    domicile="US", aum=190000),
  data.frame(ticker="VTV",    name="Vanguard Value",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Value", sector=NA, theme=NA,
    expense_ratio=0.0004, distribution_policy="distributing",
    domicile="US", aum=175000),
  data.frame(ticker="VO",     name="Vanguard Mid-Cap",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Mid Cap", sector=NA, theme=NA,
    expense_ratio=0.0004, distribution_policy="distributing",
    domicile="US", aum=65000),
  data.frame(ticker="VB",     name="Vanguard Small-Cap",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Small Cap", sector=NA, theme=NA,
    expense_ratio=0.0005, distribution_policy="distributing",
    domicile="US", aum=55000),
  data.frame(ticker="IWM",    name="iShares Russell 2000",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Small Cap", sector=NA, theme=NA,
    expense_ratio=0.0019, distribution_policy="distributing",
    domicile="US", aum=65000),
  data.frame(ticker="QQQ",    name="Invesco QQQ (NASDAQ 100)",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Large Cap Growth", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="distributing",
    domicile="US", aum=280000),
  data.frame(ticker="CNDX.L", name="iShares NASDAQ 100 UCITS (Acc)",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Large Cap Growth", sector=NA, theme=NA,
    expense_ratio=0.0033, distribution_policy="accumulating",
    domicile="IE", aum=11000),
  data.frame(ticker="EQQQ.L", name="Invesco EQQQ NASDAQ 100 UCITS (Dist)",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Large Cap Growth", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="distributing",
    domicile="IE", aum=6500),

  # --- US factors --------------------------------------------------------
  data.frame(ticker="MTUM",   name="iShares MSCI USA Momentum Factor",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Momentum", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=14000),
  data.frame(ticker="QUAL",   name="iShares MSCI USA Quality Factor",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Quality", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=47000),
  data.frame(ticker="USMV",   name="iShares MSCI USA Min Vol",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Min Vol", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=29000),
  data.frame(ticker="VLUE",   name="iShares MSCI USA Value Factor",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Value", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=9000),

  # --- Europe broad ------------------------------------------------------
  data.frame(ticker="VGK",    name="Vanguard FTSE Europe",
    asset_class="Equity", region="Europe", region_tag="europe",
    sub_class="Regional", sector=NA, theme=NA,
    expense_ratio=0.0011, distribution_policy="distributing",
    domicile="US", aum=18000),
  data.frame(ticker="IEUR",   name="iShares Core MSCI Europe",
    asset_class="Equity", region="Europe", region_tag="europe",
    sub_class="Regional", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=5500),
  data.frame(ticker="IMEU.L", name="iShares Core MSCI Europe UCITS (Acc)",
    asset_class="Equity", region="Europe", region_tag="europe",
    sub_class="Regional", sector=NA, theme=NA,
    expense_ratio=0.0012, distribution_policy="accumulating",
    domicile="IE", aum=8500),
  data.frame(ticker="EXSA.DE", name="iShares STOXX Europe 600 UCITS (Acc)",
    asset_class="Equity", region="Europe", region_tag="europe",
    sub_class="Regional", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="accumulating",
    domicile="DE", aum=15000),
  data.frame(ticker="MEUD.L", name="Xtrackers Euro Stoxx 50 UCITS (Acc)",
    asset_class="Equity", region="Europe", region_tag="europe",
    sub_class="Eurozone", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="accumulating",
    domicile="LU", aum=6200),

  # --- European countries ------------------------------------------------
  data.frame(ticker="EWG",    name="iShares MSCI Germany",
    asset_class="Equity", region="Germany", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=1800),
  data.frame(ticker="EWU",    name="iShares MSCI United Kingdom",
    asset_class="Equity", region="UK", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=2500),
  data.frame(ticker="EWQ",    name="iShares MSCI France",
    asset_class="Equity", region="France", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=800),
  data.frame(ticker="EWP",    name="iShares MSCI Spain",
    asset_class="Equity", region="Spain", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=500),
  data.frame(ticker="EWI",    name="iShares MSCI Italy",
    asset_class="Equity", region="Italy", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=600),
  data.frame(ticker="EWN",    name="iShares MSCI Netherlands",
    asset_class="Equity", region="Netherlands", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=300),
  data.frame(ticker="EWD",    name="iShares MSCI Sweden",
    asset_class="Equity", region="Sweden", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0053, distribution_policy="distributing",
    domicile="US", aum=320),
  data.frame(ticker="EWO",    name="iShares MSCI Austria",
    asset_class="Equity", region="Austria", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=90),
  data.frame(ticker="EWL",    name="iShares MSCI Switzerland",
    asset_class="Equity", region="Switzerland", region_tag="ch",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=1500),
  data.frame(ticker="CSSMI.SW", name="iShares Core SPI UCITS (Acc)",
    asset_class="Equity", region="Switzerland", region_tag="ch",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0010, distribution_policy="accumulating",
    domicile="CH", aum=3200),

  # --- Japan + Asia developed -------------------------------------------
  data.frame(ticker="EWJ",    name="iShares MSCI Japan",
    asset_class="Equity", region="Japan", region_tag="japan",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=12000),
  data.frame(ticker="IJPA.L", name="iShares Core MSCI Japan UCITS (Acc)",
    asset_class="Equity", region="Japan", region_tag="japan",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0012, distribution_policy="accumulating",
    domicile="IE", aum=5500),
  data.frame(ticker="EWA",    name="iShares MSCI Australia",
    asset_class="Equity", region="Australia", region_tag="asia_dev",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=1700),
  data.frame(ticker="EWC",    name="iShares MSCI Canada",
    asset_class="Equity", region="Canada", region_tag=NA_character_,
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=3200),
  data.frame(ticker="EWH",    name="iShares MSCI Hong Kong",
    asset_class="Equity", region="Hong Kong", region_tag="asia_dev",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=500),
  data.frame(ticker="EWS",    name="iShares MSCI Singapore",
    asset_class="Equity", region="Singapore", region_tag="asia_dev",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=600),
  data.frame(ticker="EWY",    name="iShares MSCI South Korea",
    asset_class="Equity", region="South Korea", region_tag="asia_dev",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="US", aum=4800),

  # --- Emerging markets -------------------------------------------------
  data.frame(ticker="EEM",    name="iShares MSCI Emerging Markets",
    asset_class="Equity", region="Emerging", region_tag="em",
    sub_class="Emerging Broad", sector=NA, theme=NA,
    expense_ratio=0.0068, distribution_policy="distributing",
    domicile="US", aum=30000),
  data.frame(ticker="IEMG",   name="iShares Core MSCI Emerging Markets",
    asset_class="Equity", region="Emerging", region_tag="em",
    sub_class="Emerging Broad", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=85000),
  data.frame(ticker="VWO",    name="Vanguard FTSE Emerging",
    asset_class="Equity", region="Emerging", region_tag="em",
    sub_class="Emerging Broad", sector=NA, theme=NA,
    expense_ratio=0.0008, distribution_policy="distributing",
    domicile="US", aum=78000),
  data.frame(ticker="EIMI.L", name="iShares Core MSCI EM IMI UCITS (Acc)",
    asset_class="Equity", region="Emerging", region_tag="em",
    sub_class="Emerging Broad", sector=NA, theme=NA,
    expense_ratio=0.0018, distribution_policy="accumulating",
    domicile="IE", aum=22000),
  data.frame(ticker="MCHI",   name="iShares MSCI China",
    asset_class="Equity", region="China", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="US", aum=6500),
  data.frame(ticker="INDA",   name="iShares MSCI India",
    asset_class="Equity", region="India", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0064, distribution_policy="distributing",
    domicile="US", aum=8500),
  data.frame(ticker="EWZ",    name="iShares MSCI Brazil",
    asset_class="Equity", region="Brazil", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="US", aum=5500),
  data.frame(ticker="EWT",    name="iShares MSCI Taiwan",
    asset_class="Equity", region="Taiwan", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="US", aum=4200),
  data.frame(ticker="EWW",    name="iShares MSCI Mexico",
    asset_class="Equity", region="Mexico", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=1200),
  data.frame(ticker="EZA",    name="iShares MSCI South Africa",
    asset_class="Equity", region="South Africa", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="US", aum=400),

  # --- US sectors (SPDR) ------------------------------------------------
  data.frame(ticker="XLK",    name="SPDR Technology Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector="tech", theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=65000),
  data.frame(ticker="XLV",    name="SPDR Health Care Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector="health", theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=40000),
  data.frame(ticker="XLF",    name="SPDR Financial Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector="financials", theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=42000),
  data.frame(ticker="XLE",    name="SPDR Energy Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector="energy", theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=36000),
  data.frame(ticker="XLY",    name="SPDR Consumer Discretionary Select",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector="consumer", theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=20000),
  data.frame(ticker="XLP",    name="SPDR Consumer Staples Select",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector="consumer", theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=17000),
  data.frame(ticker="XLI",    name="SPDR Industrial Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=18000),
  data.frame(ticker="XLU",    name="SPDR Utilities Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=15000),
  data.frame(ticker="XLB",    name="SPDR Materials Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=6500),
  data.frame(ticker="XLC",    name="SPDR Communication Services Select",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector="tech", theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=18000),
  data.frame(ticker="XLRE",   name="SPDR Real Estate Select Sector",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Sector", sector=NA, theme=NA,
    expense_ratio=0.0009, distribution_policy="distributing",
    domicile="US", aum=6500),

  # --- UCITS sectors (Acc, Xtrackers MSCI World Sector) -----------------
  data.frame(ticker="XDWT.DE", name="Xtrackers MSCI World Info Tech UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Sector", sector="tech", theme=NA,
    expense_ratio=0.0025, distribution_policy="accumulating",
    domicile="IE", aum=6200),
  data.frame(ticker="XDWH.DE", name="Xtrackers MSCI World Health Care UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Sector", sector="health", theme=NA,
    expense_ratio=0.0025, distribution_policy="accumulating",
    domicile="IE", aum=2800),
  data.frame(ticker="XDWF.DE", name="Xtrackers MSCI World Financials UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Sector", sector="financials", theme=NA,
    expense_ratio=0.0025, distribution_policy="accumulating",
    domicile="IE", aum=2100),
  data.frame(ticker="XDWE.DE", name="Xtrackers MSCI World Energy UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Sector", sector="energy", theme=NA,
    expense_ratio=0.0025, distribution_policy="accumulating",
    domicile="IE", aum=800),
  data.frame(ticker="XDWY.DE", name="Xtrackers MSCI World Consumer Disc UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Sector", sector="consumer", theme=NA,
    expense_ratio=0.0025, distribution_policy="accumulating",
    domicile="IE", aum=700),

  # --- Thematics --------------------------------------------------------
  data.frame(ticker="ICLN",   name="iShares Global Clean Energy",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="clean_energy",
    expense_ratio=0.0040, distribution_policy="distributing",
    domicile="US", aum=2500),
  data.frame(ticker="INRG.L", name="iShares Global Clean Energy UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="clean_energy",
    expense_ratio=0.0065, distribution_policy="accumulating",
    domicile="IE", aum=4800),
  data.frame(ticker="TAN",    name="Invesco Solar",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="clean_energy",
    expense_ratio=0.0069, distribution_policy="distributing",
    domicile="US", aum=900),
  data.frame(ticker="FAN",    name="First Trust Wind Energy",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="clean_energy",
    expense_ratio=0.0062, distribution_policy="distributing",
    domicile="US", aum=180),
  data.frame(ticker="LIT",    name="Global X Lithium & Battery Tech",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="clean_energy",
    expense_ratio=0.0075, distribution_policy="distributing",
    domicile="US", aum=1500),
  data.frame(ticker="URA",    name="Global X Uranium",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="energy", theme="uranium",
    expense_ratio=0.0069, distribution_policy="distributing",
    domicile="US", aum=3000),
  data.frame(ticker="ARKK",   name="ARK Innovation",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Thematic", sector="tech", theme="innovation",
    expense_ratio=0.0075, distribution_policy="distributing",
    domicile="US", aum=6500),
  data.frame(ticker="ARKG",   name="ARK Genomic Revolution",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="health", theme="biotech",
    expense_ratio=0.0075, distribution_policy="distributing",
    domicile="US", aum=1400),
  data.frame(ticker="IBB",    name="iShares Biotechnology",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Industry", sector="health", theme="biotech",
    expense_ratio=0.0045, distribution_policy="distributing",
    domicile="US", aum=7000),
  data.frame(ticker="ROBO",   name="ROBO Global Robotics & Automation",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="tech", theme="ai_robotics",
    expense_ratio=0.0095, distribution_policy="distributing",
    domicile="US", aum=1100),
  data.frame(ticker="BOTZ",   name="Global X Robotics & AI",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="tech", theme="ai_robotics",
    expense_ratio=0.0068, distribution_policy="distributing",
    domicile="US", aum=2700),
  data.frame(ticker="CIBR",   name="First Trust NASDAQ Cybersecurity",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="tech", theme="cyber",
    expense_ratio=0.0060, distribution_policy="distributing",
    domicile="US", aum=7500),
  data.frame(ticker="SMH",    name="VanEck Semiconductor",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Industry", sector="tech", theme="semis",
    expense_ratio=0.0035, distribution_policy="distributing",
    domicile="US", aum=24000),
  data.frame(ticker="SOXX",   name="iShares Semiconductor",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Industry", sector="tech", theme="semis",
    expense_ratio=0.0035, distribution_policy="distributing",
    domicile="US", aum=15000),
  data.frame(ticker="PHO",    name="Invesco Water Resources",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="water",
    expense_ratio=0.0060, distribution_policy="distributing",
    domicile="US", aum=2000),
  data.frame(ticker="KWEB",   name="KraneShares CSI China Internet",
    asset_class="Equity", region="China", region_tag="em",
    sub_class="Thematic", sector="tech", theme=NA,
    expense_ratio=0.0069, distribution_policy="distributing",
    domicile="US", aum=5500),
  data.frame(ticker="ESGU",   name="iShares ESG Aware MSCI USA",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="ESG", sector=NA, theme="esg",
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=13000),
  data.frame(ticker="ESGE",   name="iShares ESG Aware MSCI EM",
    asset_class="Equity", region="Emerging", region_tag="em",
    sub_class="ESG", sector=NA, theme="esg",
    expense_ratio=0.0025, distribution_policy="distributing",
    domicile="US", aum=4000),
  data.frame(ticker="SUSW.L", name="iShares MSCI World SRI UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="ESG", sector=NA, theme="esg",
    expense_ratio=0.0020, distribution_policy="accumulating",
    domicile="IE", aum=7500),

  # --- Fixed income: US ---------------------------------------------------
  data.frame(ticker="AGG",    name="iShares US Aggregate Bond",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Aggregate", sector=NA, theme=NA,
    expense_ratio=0.0003, distribution_policy="distributing",
    domicile="US", aum=115000),
  data.frame(ticker="BND",    name="Vanguard Total Bond Market",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Aggregate", sector=NA, theme=NA,
    expense_ratio=0.0003, distribution_policy="distributing",
    domicile="US", aum=120000),
  data.frame(ticker="SHY",    name="iShares 1-3yr Treasury",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Short Duration", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=28000),
  data.frame(ticker="IEF",    name="iShares 7-10yr Treasury",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Medium Duration", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=32000),
  data.frame(ticker="TLT",    name="iShares 20+yr Treasury",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Long Duration", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=50000),
  data.frame(ticker="TIP",    name="iShares TIPS",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Inflation Protected", sector=NA, theme=NA,
    expense_ratio=0.0019, distribution_policy="distributing",
    domicile="US", aum=18000),
  data.frame(ticker="LQD",    name="iShares iBoxx Investment Grade Corp",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Investment Grade", sector=NA, theme=NA,
    expense_ratio=0.0014, distribution_policy="distributing",
    domicile="US", aum=32000),
  data.frame(ticker="HYG",    name="iShares iBoxx High Yield Corp",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="High Yield", sector=NA, theme=NA,
    expense_ratio=0.0049, distribution_policy="distributing",
    domicile="US", aum=14000),
  data.frame(ticker="JNK",    name="SPDR Bloomberg High Yield",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="High Yield", sector=NA, theme=NA,
    expense_ratio=0.0040, distribution_policy="distributing",
    domicile="US", aum=9000),

  # --- Fixed income: international + EM ---------------------------------
  data.frame(ticker="BNDX",   name="Vanguard Total Intl Bond",
    asset_class="Bond", region="International", region_tag=NA_character_,
    sub_class="Aggregate", sector=NA, theme=NA,
    expense_ratio=0.0007, distribution_policy="distributing",
    domicile="US", aum=56000),
  data.frame(ticker="EMB",    name="iShares JPM USD EM Bond",
    asset_class="Bond", region="Emerging", region_tag="em",
    sub_class="Emerging Debt", sector=NA, theme=NA,
    expense_ratio=0.0039, distribution_policy="distributing",
    domicile="US", aum=14000),
  data.frame(ticker="EMLC",   name="VanEck J.P. Morgan EM Local Currency",
    asset_class="Bond", region="Emerging", region_tag="em",
    sub_class="Emerging Local", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="distributing",
    domicile="US", aum=4500),

  # --- Fixed income: UCITS accumulating ---------------------------------
  data.frame(ticker="AGGG.L", name="iShares Core Global Agg UCITS (Acc)",
    asset_class="Bond", region="Global", region_tag=NA_character_,
    sub_class="Aggregate", sector=NA, theme=NA,
    expense_ratio=0.0010, distribution_policy="accumulating",
    domicile="IE", aum=8500),
  data.frame(ticker="IEAC.L", name="iShares Core Euro Corporate UCITS (Acc)",
    asset_class="Bond", region="Europe", region_tag="europe",
    sub_class="Investment Grade", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="accumulating",
    domicile="IE", aum=11000),
  data.frame(ticker="IEAG.L", name="iShares Core Euro Aggregate UCITS (Dist)",
    asset_class="Bond", region="Europe", region_tag="europe",
    sub_class="Aggregate", sector=NA, theme=NA,
    expense_ratio=0.0025, distribution_policy="distributing",
    domicile="IE", aum=3200),
  data.frame(ticker="IHYG.L", name="iShares Euro High Yield Corp UCITS (Dist)",
    asset_class="Bond", region="Europe", region_tag="europe",
    sub_class="High Yield", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="IE", aum=5500),
  data.frame(ticker="SEMB.L", name="iShares JPM USD EM Bond UCITS (Dist)",
    asset_class="Bond", region="Emerging", region_tag="em",
    sub_class="Emerging Debt", sector=NA, theme=NA,
    expense_ratio=0.0045, distribution_policy="distributing",
    domicile="IE", aum=9500),
  data.frame(ticker="IB01.L", name="iShares $ Treasury 0-1yr UCITS (Dist)",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Short Duration", sector=NA, theme=NA,
    expense_ratio=0.0007, distribution_policy="distributing",
    domicile="IE", aum=11500),

  # --- Alternatives: REITs + commodities + crypto -----------------------
  data.frame(ticker="VNQ",    name="Vanguard US REIT",
    asset_class="Real Estate", region="US", region_tag="us",
    sub_class="REIT", sector=NA, theme=NA,
    expense_ratio=0.0012, distribution_policy="distributing",
    domicile="US", aum=35000),
  data.frame(ticker="VNQI",   name="Vanguard International REIT",
    asset_class="Real Estate", region="International", region_tag=NA_character_,
    sub_class="REIT", sector=NA, theme=NA,
    expense_ratio=0.0012, distribution_policy="distributing",
    domicile="US", aum=4200),
  data.frame(ticker="REET",   name="iShares Global REIT",
    asset_class="Real Estate", region="Global", region_tag=NA_character_,
    sub_class="REIT", sector=NA, theme=NA,
    expense_ratio=0.0014, distribution_policy="distributing",
    domicile="US", aum=3800),
  data.frame(ticker="IUSP.L", name="iShares Developed Markets Property UCITS (Dist)",
    asset_class="Real Estate", region="Global", region_tag=NA_character_,
    sub_class="REIT", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="IE", aum=2800),
  data.frame(ticker="GLD",    name="SPDR Gold Shares",
    asset_class="Commodity", region="Global", region_tag=NA_character_,
    sub_class="Precious Metals", sector=NA, theme=NA,
    expense_ratio=0.0040, distribution_policy="distributing",
    domicile="US", aum=70000),
  data.frame(ticker="SGOL",   name="abrdn Physical Gold Shares",
    asset_class="Commodity", region="Global", region_tag=NA_character_,
    sub_class="Precious Metals", sector=NA, theme=NA,
    expense_ratio=0.0017, distribution_policy="distributing",
    domicile="US", aum=2800),
  data.frame(ticker="SLV",    name="iShares Silver Trust",
    asset_class="Commodity", region="Global", region_tag=NA_character_,
    sub_class="Precious Metals", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=11500),
  data.frame(ticker="GDX",    name="VanEck Gold Miners",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Industry", sector="materials", theme=NA,
    expense_ratio=0.0051, distribution_policy="distributing",
    domicile="US", aum=13500),
  data.frame(ticker="DBC",    name="Invesco DB Commodity",
    asset_class="Commodity", region="Global", region_tag=NA_character_,
    sub_class="Broad Commodities", sector=NA, theme=NA,
    expense_ratio=0.0085, distribution_policy="distributing",
    domicile="US", aum=1300),
  data.frame(ticker="USO",    name="United States Oil Fund",
    asset_class="Commodity", region="Global", region_tag=NA_character_,
    sub_class="Energy", sector=NA, theme=NA,
    expense_ratio=0.0079, distribution_policy="distributing",
    domicile="US", aum=1300),
  data.frame(ticker="BITO",   name="ProShares Bitcoin Strategy",
    asset_class="Crypto", region="Global", region_tag=NA_character_,
    sub_class="Cryptocurrency", sector=NA, theme=NA,
    expense_ratio=0.0095, distribution_policy="distributing",
    domicile="US", aum=1800),
  data.frame(ticker="IBIT",   name="iShares Bitcoin Trust",
    asset_class="Crypto", region="Global", region_tag=NA_character_,
    sub_class="Cryptocurrency", sector=NA, theme=NA,
    expense_ratio=0.0025, distribution_policy="distributing",
    domicile="US", aum=25000),

  # ========================================================================
  # Batch 2: broader coverage
  # ========================================================================

  # --- UCITS factor ETFs (acc) ------------------------------------------
  data.frame(ticker="IWMO.L", name="iShares Edge MSCI World Momentum UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Momentum", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="accumulating",
    domicile="IE", aum=4200),
  data.frame(ticker="IWQU.L", name="iShares Edge MSCI World Quality UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Quality", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="accumulating",
    domicile="IE", aum=5500),
  data.frame(ticker="IWVL.L", name="iShares Edge MSCI World Value Factor UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Value", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="accumulating",
    domicile="IE", aum=2800),
  data.frame(ticker="MVOL.L", name="iShares Edge MSCI World Min Vol UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Min Vol", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="accumulating",
    domicile="IE", aum=3600),
  data.frame(ticker="IWSZ.L", name="iShares Edge MSCI World Size Factor UCITS (Acc)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Size", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="accumulating",
    domicile="IE", aum=320),
  data.frame(ticker="SIZE",   name="iShares MSCI USA Size Factor",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Size", sector=NA, theme=NA,
    expense_ratio=0.0015, distribution_policy="distributing",
    domicile="US", aum=1400),

  # --- Additional European countries ------------------------------------
  data.frame(ticker="EDEN",   name="iShares MSCI Denmark",
    asset_class="Equity", region="Denmark", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0053, distribution_policy="distributing",
    domicile="US", aum=180),
  data.frame(ticker="ENOR",   name="iShares MSCI Norway",
    asset_class="Equity", region="Norway", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0053, distribution_policy="distributing",
    domicile="US", aum=90),
  data.frame(ticker="EFNL",   name="iShares MSCI Finland",
    asset_class="Equity", region="Finland", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0053, distribution_policy="distributing",
    domicile="US", aum=70),
  data.frame(ticker="EIRL",   name="iShares MSCI Ireland",
    asset_class="Equity", region="Ireland", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=110),
  data.frame(ticker="EPOL",   name="iShares MSCI Poland",
    asset_class="Equity", region="Poland", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="US", aum=260),
  data.frame(ticker="TUR",    name="iShares MSCI Turkey",
    asset_class="Equity", region="Turkey", region_tag="em",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0059, distribution_policy="distributing",
    domicile="US", aum=400),
  data.frame(ticker="GREK",   name="Global X MSCI Greece",
    asset_class="Equity", region="Greece", region_tag="europe",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0058, distribution_policy="distributing",
    domicile="US", aum=220),

  # --- Dividend / yield ------------------------------------------------
  data.frame(ticker="VIG",    name="Vanguard Dividend Appreciation",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Dividend Growth", sector=NA, theme="dividend",
    expense_ratio=0.0006, distribution_policy="distributing",
    domicile="US", aum=85000),
  data.frame(ticker="VYM",    name="Vanguard High Dividend Yield",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Dividend", sector=NA, theme="dividend",
    expense_ratio=0.0006, distribution_policy="distributing",
    domicile="US", aum=55000),
  data.frame(ticker="SCHD",   name="Schwab US Dividend Equity",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Dividend", sector=NA, theme="dividend",
    expense_ratio=0.0006, distribution_policy="distributing",
    domicile="US", aum=58000),
  data.frame(ticker="DVY",    name="iShares Select Dividend",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Dividend", sector=NA, theme="dividend",
    expense_ratio=0.0038, distribution_policy="distributing",
    domicile="US", aum=18000),
  data.frame(ticker="NOBL",   name="ProShares S&P 500 Dividend Aristocrats",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Dividend Growth", sector=NA, theme="dividend",
    expense_ratio=0.0035, distribution_policy="distributing",
    domicile="US", aum=12000),
  data.frame(ticker="VHYL.L", name="Vanguard FTSE All-World HDY UCITS (Dist)",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Dividend", sector=NA, theme="dividend",
    expense_ratio=0.0029, distribution_policy="distributing",
    domicile="IE", aum=5500),

  # --- More thematics ---------------------------------------------------
  data.frame(ticker="IFRA",   name="iShares US Infrastructure",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Thematic", sector=NA, theme="infrastructure",
    expense_ratio=0.0030, distribution_policy="distributing",
    domicile="US", aum=2800),
  data.frame(ticker="GII",    name="SPDR S&P Global Infrastructure",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="infrastructure",
    expense_ratio=0.0040, distribution_policy="distributing",
    domicile="US", aum=520),
  data.frame(ticker="PAVE",   name="Global X US Infrastructure Dev",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Thematic", sector=NA, theme="infrastructure",
    expense_ratio=0.0047, distribution_policy="distributing",
    domicile="US", aum=8500),
  data.frame(ticker="ITA",    name="iShares US Aerospace & Defense",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Industry", sector=NA, theme="defense",
    expense_ratio=0.0040, distribution_policy="distributing",
    domicile="US", aum=6500),
  data.frame(ticker="XAR",    name="SPDR S&P Aerospace & Defense",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Industry", sector=NA, theme="defense",
    expense_ratio=0.0035, distribution_policy="distributing",
    domicile="US", aum=2200),
  data.frame(ticker="MOO",    name="VanEck Agribusiness",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="agribusiness",
    expense_ratio=0.0053, distribution_policy="distributing",
    domicile="US", aum=700),
  data.frame(ticker="WOOD",   name="iShares Global Timber & Forestry",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="timber",
    expense_ratio=0.0043, distribution_policy="distributing",
    domicile="US", aum=220),
  data.frame(ticker="FINX",   name="Global X FinTech",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="financials", theme="fintech",
    expense_ratio=0.0068, distribution_policy="distributing",
    domicile="US", aum=480),
  data.frame(ticker="AIQ",    name="Global X AI & Big Data",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="tech", theme="ai_robotics",
    expense_ratio=0.0068, distribution_policy="distributing",
    domicile="US", aum=2400),
  data.frame(ticker="DRIV",   name="Global X Autonomous & Electric Vehicles",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector=NA, theme="ev_autonomous",
    expense_ratio=0.0068, distribution_policy="distributing",
    domicile="US", aum=620),
  data.frame(ticker="HERO",   name="Global X Video Games & Esports",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="tech", theme="gaming",
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=230),
  data.frame(ticker="GNOM",   name="Global X Genomics & Biotechnology",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="health", theme="biotech",
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=120),
  data.frame(ticker="HACK",   name="Amplify Cybersecurity",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="tech", theme="cyber",
    expense_ratio=0.0060, distribution_policy="distributing",
    domicile="US", aum=1500),
  data.frame(ticker="BLOK",   name="Amplify Transformational Data Sharing",
    asset_class="Equity", region="Global", region_tag=NA_character_,
    sub_class="Thematic", sector="tech", theme="blockchain",
    expense_ratio=0.0071, distribution_policy="distributing",
    domicile="US", aum=450),
  data.frame(ticker="SPLV",   name="Invesco S&P 500 Low Volatility",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Min Vol", sector=NA, theme=NA,
    expense_ratio=0.0025, distribution_policy="distributing",
    domicile="US", aum=9500),
  data.frame(ticker="MOAT",   name="VanEck Morningstar Wide Moat",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Quality", sector=NA, theme=NA,
    expense_ratio=0.0046, distribution_policy="distributing",
    domicile="US", aum=15000),
  data.frame(ticker="COWZ",   name="Pacer US Cash Cows 100",
    asset_class="Equity", region="US", region_tag="us",
    sub_class="Value", sector=NA, theme="dividend",
    expense_ratio=0.0049, distribution_policy="distributing",
    domicile="US", aum=26000),

  # --- Japan + Asia variants --------------------------------------------
  data.frame(ticker="DXJ",    name="WisdomTree Japan Hedged Equity",
    asset_class="Equity", region="Japan", region_tag="japan",
    sub_class="Country", sector=NA, theme=NA,
    expense_ratio=0.0048, distribution_policy="distributing",
    domicile="US", aum=4600),
  data.frame(ticker="AIA",    name="iShares Asia 50",
    asset_class="Equity", region="Asia", region_tag="asia_dev",
    sub_class="Regional", sector=NA, theme=NA,
    expense_ratio=0.0050, distribution_policy="distributing",
    domicile="US", aum=900),
  data.frame(ticker="FM",     name="iShares MSCI Frontier & Select EM",
    asset_class="Equity", region="Frontier", region_tag="em",
    sub_class="Frontier", sector=NA, theme=NA,
    expense_ratio=0.0079, distribution_policy="distributing",
    domicile="US", aum=400),
  data.frame(ticker="CQQQ",   name="Invesco China Technology",
    asset_class="Equity", region="China", region_tag="em",
    sub_class="Thematic", sector="tech", theme=NA,
    expense_ratio=0.0070, distribution_policy="distributing",
    domicile="US", aum=700),

  # --- Fixed income: more US + alternatives -----------------------------
  data.frame(ticker="MUB",    name="iShares National Muni Bond",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Municipal", sector=NA, theme=NA,
    expense_ratio=0.0005, distribution_policy="distributing",
    domicile="US", aum=38000),
  data.frame(ticker="BKLN",   name="Invesco Senior Loan",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Bank Loans", sector=NA, theme=NA,
    expense_ratio=0.0065, distribution_policy="distributing",
    domicile="US", aum=8200),
  data.frame(ticker="CWB",    name="SPDR Bloomberg Convertible Securities",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Convertibles", sector=NA, theme=NA,
    expense_ratio=0.0040, distribution_policy="distributing",
    domicile="US", aum=4000),
  data.frame(ticker="PFF",    name="iShares Preferred & Income Securities",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Preferred", sector=NA, theme=NA,
    expense_ratio=0.0046, distribution_policy="distributing",
    domicile="US", aum=13000),
  data.frame(ticker="VCSH",   name="Vanguard Short-Term Corporate Bond",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Short Duration", sector=NA, theme=NA,
    expense_ratio=0.0004, distribution_policy="distributing",
    domicile="US", aum=35000),
  data.frame(ticker="VCIT",   name="Vanguard Intermediate-Term Corp Bond",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Medium Duration", sector=NA, theme=NA,
    expense_ratio=0.0004, distribution_policy="distributing",
    domicile="US", aum=45000),
  data.frame(ticker="VCLT",   name="Vanguard Long-Term Corp Bond",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Long Duration", sector=NA, theme=NA,
    expense_ratio=0.0004, distribution_policy="distributing",
    domicile="US", aum=7500),
  data.frame(ticker="FALN",   name="iShares Fallen Angels USD Bond",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Fallen Angels", sector=NA, theme=NA,
    expense_ratio=0.0025, distribution_policy="distributing",
    domicile="US", aum=1700),
  data.frame(ticker="SHYG",   name="iShares 0-5 Year High Yield Corp",
    asset_class="Bond", region="US", region_tag="us",
    sub_class="Short HY", sector=NA, theme=NA,
    expense_ratio=0.0030, distribution_policy="distributing",
    domicile="US", aum=5200),

  # --- Fixed income: UCITS variants -------------------------------------
  data.frame(ticker="IGLO.L", name="iShares Global Govt Bond UCITS (Dist)",
    asset_class="Bond", region="Global", region_tag=NA_character_,
    sub_class="Treasury", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="distributing",
    domicile="IE", aum=2400),
  data.frame(ticker="IGLA.L", name="iShares Global Govt Bond UCITS (Acc)",
    asset_class="Bond", region="Global", region_tag=NA_character_,
    sub_class="Treasury", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="accumulating",
    domicile="IE", aum=1400),
  data.frame(ticker="INXG.L", name="iShares GBP Index-Linked Gilts UCITS (Dist)",
    asset_class="Bond", region="UK", region_tag="europe",
    sub_class="Inflation Protected", sector=NA, theme=NA,
    expense_ratio=0.0020, distribution_policy="distributing",
    domicile="IE", aum=800),

  # --- Alternatives: more crypto + commodities --------------------------
  data.frame(ticker="ETHE",   name="Grayscale Ethereum Trust",
    asset_class="Crypto", region="Global", region_tag=NA_character_,
    sub_class="Cryptocurrency", sector=NA, theme=NA,
    expense_ratio=0.0250, distribution_policy="distributing",
    domicile="US", aum=6500),
  data.frame(ticker="FBTC",   name="Fidelity Wise Origin Bitcoin",
    asset_class="Crypto", region="Global", region_tag=NA_character_,
    sub_class="Cryptocurrency", sector=NA, theme=NA,
    expense_ratio=0.0025, distribution_policy="distributing",
    domicile="US", aum=18000),
  data.frame(ticker="ARKB",   name="ARK 21Shares Bitcoin",
    asset_class="Crypto", region="Global", region_tag=NA_character_,
    sub_class="Cryptocurrency", sector=NA, theme=NA,
    expense_ratio=0.0021, distribution_policy="distributing",
    domicile="US", aum=3200),
  data.frame(ticker="BTCE.DE", name="21Shares Bitcoin ETP",
    asset_class="Crypto", region="Global", region_tag=NA_character_,
    sub_class="Cryptocurrency", sector=NA, theme=NA,
    expense_ratio=0.0149, distribution_policy="accumulating",
    domicile="CH", aum=1200),
  data.frame(ticker="AETH.SW", name="21Shares Ethereum ETP",
    asset_class="Crypto", region="Global", region_tag=NA_character_,
    sub_class="Cryptocurrency", sector=NA, theme=NA,
    expense_ratio=0.0149, distribution_policy="accumulating",
    domicile="CH", aum=900),

  # --- Misc US large cap + value/growth detail --------------------------
  data.frame(ticker="VEU",    name="Vanguard FTSE All-World ex-US",
    asset_class="Equity", region="International", region_tag=NA_character_,
    sub_class="Regional", sector=NA, theme=NA,
    expense_ratio=0.0007, distribution_policy="distributing",
    domicile="US", aum=65000),
  data.frame(ticker="VEA",    name="Vanguard FTSE Developed Markets",
    asset_class="Equity", region="International", region_tag=NA_character_,
    sub_class="Developed", sector=NA, theme=NA,
    expense_ratio=0.0005, distribution_policy="distributing",
    domicile="US", aum=120000),
  stringsAsFactors = FALSE
)

cat("Universe size (ETFs):", nrow(u), "\n")

# Add type column
u$type <- "ETF"

# Scale AUM to USD
u$aum <- u$aum * 1e6

# -- FX pseudo-tickers ---------------------------------------------------------
fx_tickers <- c("CHFUSD=X", "EURUSD=X")
fx_meta <- data.frame(
  ticker = c(".CHFUSD", ".EURUSD"),
  name = c("CHF per USD", "EUR per USD"),
  asset_class = "FX",
  region = "Global", region_tag = NA_character_,
  sub_class = "Currency",
  sector = NA_character_, theme = NA_character_,
  expense_ratio = NA_real_,
  distribution_policy = NA_character_,
  domicile = NA_character_,
  aum = NA_real_,
  type = "FX",
  stringsAsFactors = FALSE
)

metadata <- rbind(u, fx_meta)
cat("Total rows (including FX):", nrow(metadata), "\n")

# -- Fetch monthly returns -----------------------------------------------------

cat("\nFetching monthly returns from Yahoo Finance...\n")
from_date <- "2016-01-01"
to_date <- as.character(Sys.Date())

fetch_one <- function(sym, label = sym, use_close = FALSE) {
  cat("  ", label, "... ", sep = "")
  tryCatch({
    raw <- getSymbols(sym, src = "yahoo", from = from_date, to = to_date,
      periodicity = "monthly", auto.assign = FALSE)
    px <- if (use_close) Cl(raw) else Ad(raw)
    ret <- diff(log(px))[-1]
    result <- data.frame(
      date = zoo::index(ret),
      ticker = label,
      return = as.numeric(ret),
      stringsAsFactors = FALSE
    )
    cat(nrow(result), "months\n")
    result
  }, error = function(e) {
    cat("FAILED:", conditionMessage(e), "\n")
    NULL
  })
}

returns_list <- lapply(u$ticker, fetch_one)

fx_list <- mapply(
  function(pair, pseudo) fetch_one(pair, pseudo, use_close = TRUE),
  fx_tickers, c(".CHFUSD", ".EURUSD"),
  SIMPLIFY = FALSE
)

all_returns <- do.call(rbind,
  Filter(Negate(is.null), c(returns_list, fx_list)))

cat("\nTotal return rows:", nrow(all_returns), "\n")
have_data <- unique(all_returns$ticker)
cat("Tickers with data:", length(have_data), "/", nrow(metadata), "\n")

missing <- setdiff(metadata$ticker, have_data)
if (length(missing) > 0) {
  cat("Missing:", paste(missing, collapse = ", "), "\n")
  metadata <- metadata[metadata$ticker %in% have_data, , drop = FALSE]
  cat("Dropped missing tickers from metadata. Final rows:",
    nrow(metadata), "\n")
}

# -- Build dm ------------------------------------------------------------------

portfolio_dm <- dm(metadata = metadata, returns = all_returns) |>
  dm_add_pk(metadata, ticker) |>
  dm_add_fk(returns, ticker, metadata)

saveRDS(portfolio_dm, "inst/extdata/portfolio_dm.rds")
cat("\nSaved inst/extdata/portfolio_dm.rds\n")
cat("Metadata:", nrow(metadata), "rows\n")
cat("Returns: ", nrow(all_returns), "rows\n")
